### ISSUE TITLE
Search from parameter file

### ISSUE THREAD

**Issue by VictorSanh** [Epistimio/orion#233]
Hi!

I have a `json` file in which I define all my hyper-parameters.
For instance:
```json
...
'batch_size': 3,
'dim': 768,
'dropout': 0.1
...
```
I load this json file by specifying a `--config_file` in the `args`.
Can I still use this lib to explore the parameter space (for instance to vary the `dim` size)?

Victor

**Comment by bouthilx** [comment]
Hi Victor!

Yes you can use Oríon with a configuration file for your script. We are actually planning on releasing the doc for this today. You can look at the pre-released doc meanwhile here: https://orion.readthedocs.io/en/doc-search_space/user/searchspace.html#configuration-file.

There is one issue however, for now it will only work if you specify your configuration file with `--config`. Can you modify your code to use this instead of `--config_file`? Otherwise, you can install Oríon from source and modify the file `src/orion/core/io/orion_cmdline_parser.py` at line 70 to set the default value to `config_prefix='config_file'` instead of `config_prefix=config`. This should be configurable in v0.1.6 or v0.1.7, in a couple of weeks.

**Comment by bouthilx** [comment]
Hi Victor,

Did you manage to solve your issue?

**Comment by bouthilx** [comment]
I will close this issue since we did not get any answer since Jul 2019. Please re-open it if you still have the issue.
