### ISSUE TITLE
ASHA not recognizing fidelity option

### ISSUE THREAD

**Issue by turpaultn** [Epistimio/orion#298]
Hi, 

While launching my code with the following config file:
```
algorithms:
   asha:
     seed: 1
     num_rungs: null
     num_brackets: null
 
 producer:                                                                                                                
   strategy: StubParallelStrategy
 
 database:
   host: /home/pul51/wld41/code/orion_database/orion
   name: triplet_embedding
   type: pickleddb
```

I have the following error:
```
Traceback (most recent call last):                                                                     
File "/projects/pul51/shared/calcul/users/nturpault/anaconda3/envs/pytorch/lib/python3.6/site-package    s/orion/algo/asha.py", line 86, in __init__
 fidelity_index = self.fidelity_index
File "/projects/pul51/shared/calcul/users/nturpault/anaconda3/envs/pytorch/lib/python3.6/site-package    s/orion/algo/asha.py", line 256, in fidelity_index
  return [i for i, dim in enumerate(self.space.values()) if _is_fidelity(dim)][0]
IndexError: list index out of range
...
...
 ASHA cannot be used if space does contain a fidelity dimension.
 For more information on the configuration and usage of ASHA, see
https://orion.readthedocs.io/en/develop/user/algorithms.html#asha
```

My code is launched with the following line:
```
orion hunt --config orion_config.yaml --worker-trials 1 -n try main_baseline.py --epochs~'fidelity(low=1, high=200)' --n_layers_classif~"choices([1,2])" --conv_dropout~'uniform(0., 0.5)' 
```

I'd like to know what I'm doing wrong please, because I don't find any issue about this so I guess I do something wrong.

Thanks for your work,
Best,

**Comment by bouthilx** [comment]
Hi!

Could you please confirm which version you are using and give the full stack trace of the error. I tried to reproduce the error but it works fine on my side.

From what I see the problem seems to be that the space does not contain a fidelity dimension even though you do pass one in the commandline (`--epochs~'fidelity(low=1, high=200)'`). My guess is that the prior is not detected properly by the parser and thus is parsed as a constant argument instead (like `--some 'args'` would).

Is it possible that your shell interpreter is splitting the prior into different arguments (like this `--epochs~fidelity(low=1,` and `high=200)`) ? I've seen this happen when using Oríon inside Singularity containters. To fix this you can simply remove the space `--epochs~'fidelity(low=1,high=200)'`.

One thing you could try to sort this out is replace `asha` with `random` and then visualize the info of the experiment to see how the commandline got parsed. `random` won't fail if there is no fidelity dimension so the experiment will be registered properly and you can print the info.
Use the command `orion info --config orion_config.yaml --name try` and if everything went fine you should have a Space like this

```
Space
=====
/conv_dropout: uniform(0.0, 0.5)
/epochs: fidelity(1, 200, 2)
/n_layers_classif: choices([1, 2])
```

But my guess is you'll have more something like this

```
Space
=====
/n_layers_classif: choices([1, 2])
```

**Comment by turpaultn** [comment]
Hi, 

Thank you so much for your answer, indeed you're right, replacing by ```--epochs~'fidelity(low=1,high=200)'```solved the problem.
I ran into this problem running bayesian optimizer but didn't catch this one for ASHA.

I'm sorry for this stupid mistake.
Thank you very much for the amazing tool and your answer !!!

**Comment by bouthilx** [comment]
I'm glad you managed to solve your problem. :) I don't think this is a stupid mistake. The logging and the error message did not help directly diagnosing this issue so it isn't surprising you had difficulty fixing it. Giving better logging to inform abouth the space detected could help users avoid this issue in the future. I'll look into it.

**Comment by turpaultn** [comment]
Thank you very much.
