### ISSUE TITLE
Space transformer nested with mulitple algorithms required types

### ISSUE THREAD

**Issue by donglinjy** [Epistimio/orion#368]
Space dimensions
```
Real(name=/x0, prior={uniform: (1, 2), {}}, shape=(), default value=None)
Integer(name=/x1, prior={uniform: (1, 1), {}}, shape=(), default value=None)
Categorical(name=/x2, prior={1: 0.33, 3: 0.33, 4: 0.33}, shape=(), default value=None)
```

Algorithm.requires = `['real', 'integer']`

And there is the transformed space dimensions, is this working as design? I guess the source type need only to be transformed to one `proper` target type, instead of nested all the target types.
```
Quantize(Precision(4, Real(name=/x0, prior={uniform: (1, 2), {}}, shape=(), default value=None)))
Quantize(ReverseQuantize(Integer(name=/x1, prior={uniform: (1, 1), {}}, shape=(), default value=None)))
Quantize(OneHotEncode(Enumerate(Categorical(name=/x2, prior={1: 0.33, 3: 0.33, 4: 0.33}, shape=(), default value=None))))
```

**Comment by bouthilx** [comment]
I do not see so far a use case for using the list of requirements instead of a single one. The second dimension `x1` is clearly problematic, but this is because requirements are `real` and then `integer`, so the integer dimension is turn to real and then back to integer. If we add a linear requirements to get rid of the log-priors, then something like `requires = ['real', 'linear']` would make sense.

**Comment by donglinjy** [comment]
my understanding for a list of requirements is the algorithm supports to run with multiple types. And if we actually will nest the types in requirements list, which means the later ones will nest the previous ones in the list, then why not just use only the last one.

**Comment by bouthilx** [comment]
Indeed, the list as a `or` would make more sense then as a sequence of nested requirements. Otherwise we could revert to simply using the last element until we either deprecate the nested requirements or turn it into a `or`.
