### ISSUE TITLE
orion hunt not starting a new experiment without changing random seed in orion config

### ISSUE THREAD

**Issue by JSGrondin** [Epistimio/orion#633]
**Describe the bug**
With a fresh new db (either PickleDB or MongoDB), I launch a first random search experiment with `orion vvv hunt -n test ...` and do not encounter the bug. However, when I launch a subsequent experiment with `orion vvv hunt -n test2 ...`, the experiment does not start. I am able to bypass this problem if I change the random seed in the orion config. So, everytime I launch a new experiment, I have to use a new unique random seed.

**Expected behavior**
Orion should not prevent me from running the same orion config on different experiments. 

**Steps to reproduce**
My config: 
```bash
storage:
  database:
    host: './orion/db.pkl'
    type: pickleddb
worker: 
  user_script_config: cfg
experiment:
    algorithms:
        random:
            seed: null
evc:
  ignore_code_changes: True
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.9.4
 - Oríon version: 0.1.15
 - Database: Tested both PickleDB and MongoDB and problem affects both

** Possible solution**
In the mean time, I am using v0.1.14, which doesn't have this bug.

**Comment by bouthilx** [comment]
Thanks for sharing the issue! Sorry for the delay, I was on vacation for the past 2 weeks.

I'm reporting here the conclusion of our discussion on slack.

I was unable to reproduce the issue as reported. What enabled me to reproduce the issue was using the same search space of a single HP with prior `loguniform(1e-4, 1e-2, precision=2)` which limited the search space to 181 possible values. Random search got stuck trying to sample 1000 different values.

The difference with v0.1.14 is that until v0.1.15 the algos would sample trials one by one, thus random search would be able to sample 181 trials at which point it would get stuck. In v0.1.15 algos try to sample as many trials as possible to have more efficient I/O.

I fixed the issue in PR #635, adding a cardinality count for loguniform dimensions so that algos do not get stuck anymore.
